language: node_js
node_js:
  - "10"
services:
  - mongodb
cache:
  directories:
    - "node_modules"
  yarn: true
script:
  - npm install
  - npm install coveralls
  - yarn travis
after_success:
  - coveralls < coverage/lcov.info

